package:
  name: variantkey-src
  version: 5.4.2

source:
  path: ../..

build:
  number: 1

about:
  home: https://github.com/tecnickcom/variantkey
  license: MIT
  license_file: LICENSE
  summary: VariantKey library C header only source code
