package:
  name: variantkey-vk
  version: 5.4.5

source:
  path: ../..

build:
  number: 1

about:
  home: https://github.com/tecnickcom/variantkey
  license: MIT
  license_file: LICENSE
  summary: VariantKey fast encoder command line application
