// VariantKey
//
// nrvk.h
//
// @category   Libraries
// @author     Nicola Asuni <info@tecnick.com>
// @link       https://github.com/tecnickcom/variantkey
// @license    MIT [LICENSE](https://raw.githubusercontent.com/tecnickcom/variantkey/main/LICENSE)

/**
 * @file nrvk.h
 * @brief Lookup of the REF and ALT strings of a non-reversible VariantKey.
 *
 * Retrieves the REF and ALT strings of a VariantKey from a memory mapped binary
 * lookup table, for the keys that the reversible encoding cannot represent.
 *
 * The binary file can be generated by the `resources/tools/nrvk.sh` script from
 * a TSV file with the following format:
 *
 *     [16 BYTE VARIANTKEY HEX]\t[REF STRING]\t[ALT STRING]\n...
 *
 * for example:
 *
 *     b800c35bbcece603	AAAAAAAAGG	AG
 *     1800c351f61f65d3	A	AAGAAAGAAAG
 */

#ifndef VARIANTKEY_NRVK_H
#define VARIANTKEY_NRVK_H

#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "binsearch.h"
#include "variantkey.h"

#ifndef ALLELE_MAXSIZE
#define ALLELE_MAXSIZE 256 //!< Maximum allele length.
#endif

/**
 * @brief The decoded components of a VariantKey.
 */
typedef struct variantkey_rev_t
{
    char chrom[3];             //!< Chromosome.
    uint32_t pos;              //!< Reference position, with the first base having position 0.
    char ref[ALLELE_MAXSIZE];  //!< Reference allele
    char alt[ALLELE_MAXSIZE];  //!< Alternate allele
    size_t sizeref;            //!< Length of reference allele
    size_t sizealt;            //!< Length of alternate allele
} variantkey_rev_t;

/**
 * @brief Pointers to the columns of the NRVK memory mapped file.
 */
typedef struct nrvk_cols_t
{
    const uint64_t *vk;      //!< Pointer to the VariantKey column.
    const uint64_t *offset;  //!< Pointer to the Offset column.
    const uint8_t  *data;    //!< Pointer to the Data column.
    uint64_t nrows;          //!< Number of rows.
} nrvk_cols_t;

/**
 * @brief Memory maps the NRVK binary file.
 *
 * @param file  Path to the file to map.
 * @param mf    Structure containing the memory mapped file.
 * @param nvc   Structure containing the pointers to the memory mapped file columns.
 */
static inline void mmap_nrvk_file(const char *file, mmfile_t *mf, nrvk_cols_t *nvc)
{
    mmap_binfile(file, mf);
    nvc->vk = (const uint64_t *)(mf->src + mf->index[0]);
    nvc->offset = (const uint64_t *)(mf->src + mf->index[1]);
    nvc->data = (const uint8_t *)(mf->src + mf->index[2]);
    nvc->nrows = mf->nrows;
}

/**
 * @brief Returns the REF and ALT strings stored at the given row.
 *
 * @param nvc      Structure containing the pointers to the memory mapped file columns.
 * @param pos      Row number.
 * @param ref      REF string buffer to be returned (it must be sized ALLELE_MAXSIZE bytes).
 * @param sizeref  Pointer to the returned length of the ref string, excluding the terminating null byte.
 * @param alt      ALT string buffer to be returned (it must be sized ALLELE_MAXSIZE bytes).
 * @param sizealt  Pointer to the returned length of the alt string, excluding the terminating null byte.
 *
 * @return The total number of REF+ALT characters, or 0 if the row does not exist.
 */
static inline size_t get_nrvk_ref_alt_by_pos(nrvk_cols_t nvc, uint64_t pos, char *ref, size_t *sizeref, char *alt, size_t *sizealt)
{
    if (pos >= nvc.nrows)
    {
        return 0; // not found
    }
    const uint8_t *data = (nvc.data + *(nvc.offset + pos));
    *sizeref = (size_t)(*(data++));
    *sizealt = (size_t)(*(data++));
    memcpy(ref, data, *sizeref);
    ref[*sizeref] = 0;
    memcpy(alt, (data + *sizeref), *sizealt);
    alt[*sizealt] = 0;
    return (*sizeref + *sizealt);
}

/**
 * @brief Looks up the REF and ALT strings of a VariantKey.
 *
 * @param nvc      Structure containing the pointers to the memory mapped file columns.
 * @param vk       VariantKey to search.
 * @param ref      REF string buffer to be returned (it must be sized ALLELE_MAXSIZE bytes).
 * @param sizeref  Pointer to the returned length of the ref string, excluding the terminating null byte.
 * @param alt      ALT string buffer to be returned (it must be sized ALLELE_MAXSIZE bytes).
 * @param sizealt  Pointer to the returned length of the alt string, excluding the terminating null byte.
 *
 * @return The total number of REF+ALT characters, or 0 if the VariantKey is not found.
 */
static inline size_t find_ref_alt_by_variantkey(nrvk_cols_t nvc, uint64_t vk, char *ref, size_t *sizeref, char *alt, size_t *sizealt)
{
    uint64_t first = 0;
    uint64_t max = nvc.nrows;
    uint64_t found = col_find_first_uint64_t(nvc.vk, &first, &max, vk);
    return get_nrvk_ref_alt_by_pos(nvc, found, ref, sizeref, alt, sizealt);
}

/**
 * @brief Reverses a VariantKey into its CHROM, POS, REF and ALT components.
 *
 * The reversible encoding is used when possible, otherwise the alleles are
 * looked up in the memory mapped table.
 *
 * @param nvc      Structure containing the pointers to the memory mapped file columns.
 * @param vk       VariantKey code.
 * @param rev      Structure containing the return values.
 *
 * @return The total number of REF+ALT characters, or 0 if the VariantKey is neither reversible nor found.
 */
static inline size_t reverse_variantkey(nrvk_cols_t nvc, uint64_t vk, variantkey_rev_t *rev)
{
    decode_chrom(extract_variantkey_chrom(vk), rev->chrom);
    rev->pos = extract_variantkey_pos(vk);
    size_t len = decode_refalt(extract_variantkey_refalt(vk), rev->ref, &rev->sizeref, rev->alt, &rev->sizealt);
    if ((len == 0) && (nvc.nrows > 0))
    {
        len = find_ref_alt_by_variantkey(nvc, vk, rev->ref, &rev->sizeref, rev->alt, &rev->sizealt);
    }
    return len;
}

/**
 * @brief Returns the REF length of a VariantKey.
 *
 * @param nvc      Structure containing the pointers to the memory mapped file columns.
 * @param vk       VariantKey code.
 *
 * @return The REF length, or 0 if the VariantKey is neither reversible nor found.
 */
static inline size_t get_variantkey_ref_length(nrvk_cols_t nvc, uint64_t vk)
{
    if ((vk & 0x1) == 0) // check last bit for reversible encoding
    {
        return ((vk & 0x0000000078000000) >> 27); // [00000000 00000000 00000000 00000000 01111000 00000000 00000000 00000000]
    }
    uint64_t first = 0;
    uint64_t max = nvc.nrows;
    uint64_t found = col_find_first_uint64_t(nvc.vk, &first, &max, vk);
    if (found >= nvc.nrows)
    {
        return 0; // not found
    }
    return (size_t)(*(nvc.data + *(nvc.offset + found)));
}

/**
 * @brief Returns the end position of a VariantKey (POS + REF length).
 *
 * @param nvc      Structure containing the pointers to the memory mapped file columns.
 * @param vk       VariantKey code.
 *
 * @return The variant end position.
 */
static inline uint32_t get_variantkey_endpos(nrvk_cols_t nvc, uint64_t vk)
{
    return (extract_variantkey_pos(vk) + (uint32_t)get_variantkey_ref_length(nvc, vk));
}

/**
 * @brief Returns the CHROM and START POS section of a VariantKey.
 *
 * @param vk VariantKey code.
 *
 * @return CHROM + START POS.
 */
static inline uint64_t get_variantkey_chrom_startpos(uint64_t vk)
{
    return (vk >> VKSHIFT_POS);
}

/**
 * @brief Returns the CHROM and END POS of a VariantKey.
 *
 * @param nvc   Structure containing the pointers to the memory mapped file columns.
 * @param vk    VariantKey code.
 *
 * @return CHROM + END POS.
 */
static inline uint64_t get_variantkey_chrom_endpos(nrvk_cols_t nvc, uint64_t vk)
{
    return (((vk & VKMASK_CHROM) >> VKSHIFT_POS) | (uint64_t)get_variantkey_endpos(nvc, vk));
}

/**
 * @brief Writes the content of the NRVK memory mapped file as a TSV file.
 *
 * An existing file is replaced. For the reverse operation see the
 * `resources/tools/nrvk.sh` script.
 *
 * @param nvc      Structure containing the pointers to the memory mapped file columns.
 * @param tsvfile  Output TSV file name.
 *
 * @return The number of written bytes, or 0 if the file cannot be opened.
 */
static inline size_t nrvk_bin_to_tsv(nrvk_cols_t nvc, const char *tsvfile)
{
    FILE *fp = NULL;
    size_t sizeref = 0, sizealt = 0, len = 0;
    char ref[ALLELE_MAXSIZE];
    char alt[ALLELE_MAXSIZE];
    uint64_t i = 0;
    fp = fopen(tsvfile, "we");
    if (fp == NULL)
    {
        return 0;
    }
    for (i = 0; i < nvc.nrows; i++)
    {
        // 19 = 16 hexadecimal digits of the VariantKey, 2 tabs and 1 newline
        len += (get_nrvk_ref_alt_by_pos(nvc, i, ref, &sizeref, alt, &sizealt) + 19);
        (void) fprintf(fp, "%016" PRIx64 "\t%s\t%s\n", nvc.vk[i], ref, alt);
    }
    (void) fclose(fp);
    return len;
}

#endif  // VARIANTKEY_NRVK_H
