// VariantKey
//
// rsidvar.h
//
// @category   Libraries
// @author     Nicola Asuni <info@tecnick.com>
// @link       https://github.com/tecnickcom/variantkey
// @license    MIT [LICENSE](https://raw.githubusercontent.com/tecnickcom/variantkey/main/LICENSE)

/**
 * @file rsidvar.h
 * @brief Lookup between VariantKey and rsID.
 *
 * Searches memory mapped binary files made of two columns sorted in ascending
 * order by the first one. The files can also be in Apache Arrow File format
 * with a single RecordBatch, or in Feather format.
 *
 * rsvk.bin maps rsID to VariantKey and is generated by the
 * `resources/tools/rsvk.sh` script; its first column contains the rsID.
 *
 * vkrs.bin maps VariantKey to rsID and is generated by the
 * `resources/tools/vkrs.sh` script; its first column contains the VariantKey.
 */

#ifndef VARIANTKEY_RSIDVAR_H
#define VARIANTKEY_RSIDVAR_H

#include <inttypes.h>
#include <stdint.h>
#include "binsearch.h"

/**
 * @brief Pointers to the columns of an RSVK or VKRS memory mapped file.
 */
typedef struct rsidvar_cols_t
{
    const uint64_t *vk;  //!< Pointer to the VariantKey column.
    const uint32_t *rs;  //!< Pointer to the rsID column.
    uint64_t nrows;      //!< Number of rows.
} rsidvar_cols_t;

/**
 * @brief Memory maps the VKRS binary file.
 *
 * @param file  Path to the file to map.
 * @param mf    Structure containing the memory mapped file.
 * @param cvr   Structure containing the pointers to the VKRS memory mapped file columns.
 */
static inline void mmap_vkrs_file(const char *file, mmfile_t *mf, rsidvar_cols_t *cvr)
{
    mmap_binfile(file, mf);
    cvr->vk = (const uint64_t *)(mf->src + mf->index[0]);
    cvr->rs = (const uint32_t *)(mf->src + mf->index[1]);
    cvr->nrows = mf->nrows;
}

/**
 * @brief Memory maps the RSVK binary file.
 *
 * @param file  Path to the file to map.
 * @param mf    Structure containing the memory mapped file.
 * @param crv   Structure containing the pointers to the RSVK memory mapped file columns.
 */
static inline void mmap_rsvk_file(const char *file, mmfile_t *mf, rsidvar_cols_t *crv)
{
    mmap_binfile(file, mf);
    crv->rs = (const uint32_t *)(mf->src + mf->index[0]);
    crv->vk = (const uint64_t *)(mf->src + mf->index[1]);
    crv->nrows = mf->nrows;
}

/**
 * @brief Limits the end of a search range to the rows the file holds.
 *
 * The search functions read every row of the range without checking it, so a
 * "last" that is above the number of rows reads past the end of the mapping.
 * The bindings take that argument from their caller, so it is clamped here
 * rather than in each of them.
 *
 * @param crv   Structure containing the pointers to the memory mapped file columns.
 * @param last  Row where to end the search, up to but not including.
 *
 * @return The end of the range, at most the number of rows.
 */
static inline uint64_t rsidvar_clamp_last(rsidvar_cols_t crv, uint64_t last)
{
    return ((last > crv.nrows) ? crv.nrows : last);
}

/**
 * @brief Returns the first VariantKey associated with an rsID.
 *
 * @param crv       Structure containing the pointers to the RSVK memory mapped file columns.
 * @param first     Pointer to the first row of the range to search. It returns the row of the record found.
 * @param last      Row where to end the search, up to but not including.
 * @param rsid      rsID to search.
 *
 * @return The VariantKey, or 0 if not found.
 */
static inline uint64_t find_rv_variantkey_by_rsid(rsidvar_cols_t crv, uint64_t *first, uint64_t last, uint32_t rsid)
{
    last = rsidvar_clamp_last(crv, last);
    uint64_t max = last;
    uint64_t found = col_find_first_le_uint32_t(crv.rs, first, &max, rsid);
    if (found >= last)
    {
        return 0;
    }
    *first = found;
    return *(crv.vk + found);
}

/**
 * @brief Returns the next VariantKey associated with an rsID.
 *
 * Call this in a loop after find_rv_variantkey_by_rsid to get all the
 * VariantKeys associated with the same rsID.
 *
 * @param crv       Structure containing the pointers to the RSVK memory mapped file columns.
 * @param pos       Pointer to the current row. It returns the row of the next record.
 * @param last      Row where to end the search, up to but not including.
 * @param rsid      rsID to search.
 *
 * @return The VariantKey, or 0 if there is no next record.
 */
static inline uint64_t get_next_rv_variantkey_by_rsid(rsidvar_cols_t crv, uint64_t *pos, uint64_t last, uint32_t rsid)
{
    last = rsidvar_clamp_last(crv, last);
    if (col_has_next_le_uint32_t(crv.rs, pos, last, rsid))
    {
        return *(crv.vk + *pos);
    }
    return 0;
}

/**
 * @brief Returns the first rsID associated with a VariantKey.
 *
 * @param cvr       Structure containing the pointers to the VKRS memory mapped file columns.
 * @param first     Pointer to the first row of the range to search. It returns the row of the record found.
 * @param last      Row where to end the search, up to but not including.
 * @param vk        VariantKey to search.
 *
 * @return The rsID, or 0 if not found.
 */
static inline uint32_t find_vr_rsid_by_variantkey(rsidvar_cols_t cvr, uint64_t *first, uint64_t last, uint64_t vk)
{
    last = rsidvar_clamp_last(cvr, last);
    uint64_t max = last;
    uint64_t found = col_find_first_le_uint64_t(cvr.vk, first, &max, vk);
    if (found >= last)
    {
        return 0; // not found
    }
    *first = found;
    return *(cvr.rs + found);
}

/**
 * @brief Returns the next rsID associated with a VariantKey.
 *
 * Call this in a loop after find_vr_rsid_by_variantkey to get all the rsIDs
 * associated with the same VariantKey.
 *
 * @param cvr       Structure containing the pointers to the VKRS memory mapped file columns.
 * @param pos       Pointer to the current row. It returns the row of the next record.
 * @param last      Row where to end the search, up to but not including.
 * @param vk        VariantKey to search.
 *
 * @return The rsID, or 0 if there is no next record.
 */
static inline uint32_t get_next_vr_rsid_by_variantkey(rsidvar_cols_t cvr, uint64_t *pos, uint64_t last, uint64_t vk)
{
    last = rsidvar_clamp_last(cvr, last);
    if (col_has_next_le_uint64_t(cvr.vk, pos, last, vk))
    {
        return *(cvr.rs + *pos);
    }
    return 0;
}

/**
 * @brief Returns the first rsID of a CHROM and POS range.
 *
 * The first and last rows are narrowed in place to the rows covered by the range.
 *
 * @param cvr       Structure containing the pointers to the VKRS memory mapped file columns.
 * @param first     Pointer to the first row of the range to search. It returns the first row of the range found.
 * @param last      Pointer to the row where to end the search, up to but not including. It returns the end of the range found.
 * @param chrom     Encoded chromosome number.
 * @param pos_min   Start reference position, with the first base having position 0.
 * @param pos_max   End reference position, with the first base having position 0.
 *
 * @return The rsID, or 0 if the range is empty.
 */
static inline uint32_t find_vr_chrompos_range(rsidvar_cols_t cvr, uint64_t *first, uint64_t *last, uint8_t chrom, uint32_t pos_min, uint32_t pos_max)
{
    const uint64_t ckey = ((uint64_t)chrom << 59);
    *last = rsidvar_clamp_last(cvr, *last);
    uint64_t min = *first;
    uint64_t max = *last;
    *first = col_find_first_sub_le_uint64_t(cvr.vk, 0, 32, &min, &max, (ckey | ((uint64_t)pos_min << 31)) >> 31);
    if (*first >= *last)
    {
        return 0;
    }
    // A find_last converges to the row past the last one that is not above the
    // key and writes it to "last" whether or not the key itself is present, so
    // the range ends at pos_max even when no row matches it exactly.
    min = *first;
    max = *last;
    (void)col_find_last_sub_le_uint64_t(cvr.vk, 0, 32, &min, &max, ((ckey | ((uint64_t)pos_max << 31)) >> 31));
    *last = max;
    if (*first >= *last)
    {
        return 0; // the range is empty
    }
    return *(cvr.rs + *first);
}

#endif  // VARIANTKEY_RSIDVAR_H
