// VariantKey
//
// rsidvar.h
//
// @category   Libraries
// @author     Nicola Asuni <info@tecnick.com>
// @link       https://github.com/tecnickcom/variantkey
// @license    MIT [LICENSE](https://raw.githubusercontent.com/tecnickcom/variantkey/main/LICENSE)

/**
 * @file rsidvar.h
 * @brief Lookup between VariantKey and rsID.
 *
 * Searches memory mapped binary files made of two columns sorted in ascending
 * order by the first one. The files can also be in Apache Arrow File format
 * with a single RecordBatch, or in Feather format.
 *
 * rsvk.bin maps rsID to VariantKey and is generated by the
 * `resources/tools/rsvk.sh` script; its first column contains the rsID.
 *
 * vkrs.bin maps VariantKey to rsID and is generated by the
 * `resources/tools/vkrs.sh` script; its first column contains the VariantKey.
 */

#ifndef VARIANTKEY_RSIDVAR_H
#define VARIANTKEY_RSIDVAR_H

#include <inttypes.h>
#include <stdint.h>
#include "binsearch.h"

/**
 * @brief Pointers to the columns of an RSVK or VKRS memory mapped file.
 */
typedef struct rsidvar_cols_t
{
    const uint64_t *vk;  //!< Pointer to the VariantKey column.
    const uint32_t *rs;  //!< Pointer to the rsID column.
    uint64_t nrows;      //!< Number of rows.
} rsidvar_cols_t;

/**
 * @brief Memory maps the VKRS binary file.
 *
 * @param file  Path to the file to map.
 * @param mf    Structure containing the memory mapped file.
 * @param cvr   Structure containing the pointers to the VKRS memory mapped file columns.
 */
static inline void mmap_vkrs_file(const char *file, mmfile_t *mf, rsidvar_cols_t *cvr)
{
    mmap_binfile(file, mf);
    cvr->vk = (const uint64_t *)(mf->src + mf->index[0]);
    cvr->rs = (const uint32_t *)(mf->src + mf->index[1]);
    cvr->nrows = mf->nrows;
}

/**
 * @brief Memory maps the RSVK binary file.
 *
 * @param file  Path to the file to map.
 * @param mf    Structure containing the memory mapped file.
 * @param crv   Structure containing the pointers to the RSVK memory mapped file columns.
 */
static inline void mmap_rsvk_file(const char *file, mmfile_t *mf, rsidvar_cols_t *crv)
{
    mmap_binfile(file, mf);
    crv->rs = (const uint32_t *)(mf->src + mf->index[0]);
    crv->vk = (const uint64_t *)(mf->src + mf->index[1]);
    crv->nrows = mf->nrows;
}

/**
 * @brief Returns the first VariantKey associated with an rsID.
 *
 * @param crv       Structure containing the pointers to the RSVK memory mapped file columns.
 * @param first     Pointer to the first row of the range to search. It returns the row of the record found.
 * @param last      Row where to end the search, up to but not including.
 * @param rsid      rsID to search.
 *
 * @return The VariantKey, or 0 if not found.
 */
static inline uint64_t find_rv_variantkey_by_rsid(rsidvar_cols_t crv, uint64_t *first, uint64_t last, uint32_t rsid)
{
    uint64_t max = last;
    uint64_t found = col_find_first_uint32_t(crv.rs, first, &max, rsid);
    if (found >= last)
    {
        return 0;
    }
    *first = found;
    return *(crv.vk + found);
}

/**
 * @brief Returns the next VariantKey associated with an rsID.
 *
 * Call this in a loop after find_rv_variantkey_by_rsid to get all the
 * VariantKeys associated with the same rsID.
 *
 * @param crv       Structure containing the pointers to the RSVK memory mapped file columns.
 * @param pos       Pointer to the current row. It returns the row of the next record.
 * @param last      Row where to end the search, up to but not including.
 * @param rsid      rsID to search.
 *
 * @return The VariantKey, or 0 if there is no next record.
 */
static inline uint64_t get_next_rv_variantkey_by_rsid(rsidvar_cols_t crv, uint64_t *pos, uint64_t last, uint32_t rsid)
{
    if (col_has_next_uint32_t(crv.rs, pos, last, rsid))
    {
        return *(crv.vk + *pos);
    }
    return 0;
}

/**
 * @brief Returns the first rsID associated with a VariantKey.
 *
 * @param cvr       Structure containing the pointers to the VKRS memory mapped file columns.
 * @param first     Pointer to the first row of the range to search. It returns the row of the record found.
 * @param last      Row where to end the search, up to but not including.
 * @param vk        VariantKey to search.
 *
 * @return The rsID, or 0 if not found.
 */
static inline uint32_t find_vr_rsid_by_variantkey(rsidvar_cols_t cvr, uint64_t *first, uint64_t last, uint64_t vk)
{
    uint64_t max = last;
    uint64_t found = col_find_first_uint64_t(cvr.vk, first, &max, vk);
    if (found >= last)
    {
        return 0; // not found
    }
    *first = found;
    return *(cvr.rs + found);
}

/**
 * @brief Returns the next rsID associated with a VariantKey.
 *
 * Call this in a loop after find_vr_rsid_by_variantkey to get all the rsIDs
 * associated with the same VariantKey.
 *
 * @param cvr       Structure containing the pointers to the VKRS memory mapped file columns.
 * @param pos       Pointer to the current row. It returns the row of the next record.
 * @param last      Row where to end the search, up to but not including.
 * @param vk        VariantKey to search.
 *
 * @return The rsID, or 0 if there is no next record.
 */
static inline uint32_t get_next_vr_rsid_by_variantkey(rsidvar_cols_t cvr, uint64_t *pos, uint64_t last, uint64_t vk)
{
    if (col_has_next_uint64_t(cvr.vk, pos, last, vk))
    {
        return *(cvr.rs + *pos);
    }
    return 0;
}

/**
 * @brief Returns the row past the last one whose CHROM+POS is not above the given key.
 *
 * Plain upper-bound binary search on the CHROM+POS prefix of the VariantKey
 * column. Unlike col_find_last_sub_uint64_t, which returns the initial value of
 * "last" when the searched value is absent, this always returns a real bound.
 *
 * @param vk     Pointer to the VariantKey column.
 * @param first  First row of the search range.
 * @param last   Row past the last one of the search range.
 * @param key    CHROM+POS key to bound.
 *
 * @return The row past the last one whose CHROM+POS is less than or equal to key.
 */
static inline uint64_t rsidvar_upper_bound_chrompos(const uint64_t *vk, uint64_t first, uint64_t last, uint64_t key)
{
    while (first < last)
    {
        uint64_t middle = (first + ((last - first) >> 1));
        if ((vk[middle] >> 31) <= key)
        {
            first = (middle + 1);
        }
        else
        {
            last = middle;
        }
    }
    return first;
}

/**
 * @brief Returns the first rsID of a CHROM and POS range.
 *
 * The first and last rows are narrowed in place to the rows covered by the range.
 *
 * @param cvr       Structure containing the pointers to the VKRS memory mapped file columns.
 * @param first     Pointer to the first row of the range to search. It returns the first row of the range found.
 * @param last      Pointer to the row where to end the search, up to but not including. It returns the end of the range found.
 * @param chrom     Encoded chromosome number.
 * @param pos_min   Start reference position, with the first base having position 0.
 * @param pos_max   End reference position, with the first base having position 0.
 *
 * @return The rsID, or 0 if the range is empty.
 */
static inline uint32_t find_vr_chrompos_range(rsidvar_cols_t cvr, uint64_t *first, uint64_t *last, uint8_t chrom, uint32_t pos_min, uint32_t pos_max)
{
    uint64_t ckey = ((uint64_t)chrom << 59);
    uint64_t min = *first;
    uint64_t max = *last;
    *first = col_find_first_sub_uint64_t(cvr.vk, 0, 32, &min, &max, (ckey | ((uint64_t)pos_min << 31)) >> 31);
    if (*first >= *last)
    {
        return 0;
    }
    // rsidvar_upper_bound_chrompos returns the position of the first row above
    // pos_max, so the range ends at pos_max even when no row matches it exactly.
    *last = rsidvar_upper_bound_chrompos(cvr.vk, *first, *last, ((ckey | ((uint64_t)pos_max << 31)) >> 31));
    if (*first >= *last)
    {
        return 0; // the range is empty
    }
    return *(cvr.rs + *first);
}

#endif  // VARIANTKEY_RSIDVAR_H
